import java.util.*;

class Solution {
    public int countTrapezoids(int[][] points) {
            int n = points.length;

                    // cnt1: slope k -> (line-intercept b -> how many segments on that line)
                            Map<Double, Map<Double, Integer>> cnt1 = new HashMap<>(n * n);

                                    // cnt2: midpoint -> (slope k -> how many segments share this midpoint)
                                            Map<Long, Map<Double, Integer>> cnt2 = new HashMap<>(n * n);

                                                    for (int i = 0; i < n; ++i) {
                                                                int x1 = points[i][0], y1 = points[i][1];
                                                                            for (int j = i + 1; j < n; ++j) {
                                                                                            int x2 = points[j][0], y2 = points[j][1];

                                                                                                            int dx = x2 - x1, dy = y2 - y1;

                                                                                                                            // slope
                                                                                                                                            double k = (dx == 0 ? Double.POSITIVE_INFINITY : (double) dy / dx);

                                                                                                                                                            // line intercept (note: special handling for vertical line)
                                                                                                                                                                            double b = dx == 0 ? x1 : (double)(y1 * dx - x1 * dy) / dx;

                                                                                                                                                                                            if (k == -0.0) k = 0.0;
                                                                                                                                                                                                            if (b == -0.0) b = 0.0;

                                                                                                                                                                                                                            cnt1.computeIfAbsent(k, _ -> new HashMap<>())
                                                                                                                                                                                                                                                .merge(b, 1, Integer::sum);

                                                                                                                                                                                                                                                                // midpoint encoding
                                                                                                                                                                                                                                                                                long mx = (long)(x1 + x2);
                                                                                                                                                                                                                                                                                                long my = (long)(y1 + y2);
                                                                                                                                                                                                                                                                                                                long midKey = (mx << 32) ^ (my & 0xffffffffL);

                                                                                                                                                                                                                                                                                                                                cnt2.computeIfAbsent(midKey, _ -> new HashMap<>())
                                                                                                                                                                                                                                                                                                                                                    .merge(k, 1, Integer::sum);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                int ans = 0;

                                                                                                                                                                                                                                                                                                                                                                                        // Step 1: count ALL valid pairs of parallel segments on different parallel lines
                                                                                                                                                                                                                                                                                                                                                                                                for (Map<Double, Integer> group : cnt1.values()) {
                                                                                                                                                                                                                                                                                                                                                                                                            int prefix = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                        for (int cnt : group.values()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        ans += prefix * cnt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        prefix += cnt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Step 2: subtract INVALID pairs (segments with same midpoint)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (Map<Double, Integer> group : cnt2.values()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int prefix = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int cnt : group.values()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ans -= prefix * cnt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prefix += cnt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    